### ISSUE TITLE
FakeDatasetFactory cannot be resolved

### ISSUE THREAD

**Issue by samehkamaleldin** [matt-gardner/pra#10]
I checked out `v3.0`then I ran `sbt test`and I got the following error

``` scala
[error] ...  pra/src/test/scala/edu/cmu/ml/rtw/pra/config/SpecFileReaderSpec.scala:4: object FakeDatasetFactory is not a member of package edu.cmu.ml.rtw.pra.experiments
[error] import edu.cmu.ml.rtw.pra.experiments.FakeDatasetFactory
[error] one error found
[error] (test:compileIncremental) Compilation failed
```

I've tried `v2.0`and It's working so I think this error is related to `v3.0` only.

**Comment by matt-gardner** [comment]
You're right, I looked into that, and it's apparently broken for reasons I couldn't easily figure out.  That version is pretty out of date, though, and I think it's just the test that's broken, not the main code.  I just added a tag for version 3.3 - you might want to try checking that out instead.  If you have particular questions about what you're doing, I'm happy to try to answer those, too.
