### ISSUE TITLE
Have you tried different machine learning models else Logestic Regression

### ISSUE THREAD

**Issue by samehkamaleldin** [matt-gardner/pra#11]
Have you tried using different machine learning models for the learning path else `logistic regression` ?
for example `support vector machines` ?! 

If `yes`, Is there any available report or publication regarding results of these models with `SFE` and `PRA` ?

**Comment by matt-gardner** [comment]
Yes, it's been tried, though I didn't spend a whole lot of time trying to make it work well.  A student I was working with implemented this as part of a class project.  You can see the report [here](http://www.contrib.andrew.cmu.edu/~kdagrawa/documents/10605report.pdf); look particularly at section 3.3 and table 7.  This is still in the codebase, and you can run PRA / SFE with an SVM if you want.  See the example experiment specifications [here](https://github.com/matt-gardner/pra/tree/master/examples/experiment_specs/nell/new_models).  I'm certain that those files with crash with a current version of the code, though; the parameters need to be updated.  The important part is the "learning" section.
