### ISSUE TITLE
run sfe_bfs_pra_anyrel 

### ISSUE THREAD

**Issue by papisw** [matt-gardner/pra#17]
I try to follow http://rtw.ml.cmu.edu/emnlp2015_sfe/ to replicate the results reported in emnlp 2015. 
Even though I can get the code run until the end, I get an error 
INFO models.MalletLogisticRegression: Using L1 regularization
cc.mallet.optimize.OrthantWiseLimitedMemoryBFGS
INFO: getValue() (MalletLogisticRegression$LogRegOptimizable.getValue()

Is it common or I mess up something when I set up the code.
Thanks,

**Comment by samehkamaleldin** [comment]
I think the error messages shown while running is okay, It will still work despite that.

**Comment by matt-gardner** [comment]
That is how sbt shows things when a subprocess prints to stderr.  MALLET logs to stderr.  This is not an error.
