### ISSUE TITLE
SET UP WITH Different data set

### ISSUE THREAD

**Issue by papisw** [matt-gardner/pra#18]
I want to run the code with my data set but I am not sure how to correctly create an input data (graph, metadata files)
I currently have a database which contains 3 columns (subject, object and relationship column.)
How can I convert this data into a graph format (stored in graph.tgz)? What are included in the metadata and what are their format? 

Thanks

**Comment by matt-gardner** [comment]
Have you looked at [the documentation](http://matt-gardner.github.io/pra/input/graphs.html)?

**Comment by papisw** [comment]
I did but it's still not clear to me how to get contents inside the graph directory.  
According to http://rtw.ml.cmu.edu/emnlp2015_sfe/, it seems like I have to have the graph directory.
Shouldn't I provide contents in the graph directory as input if I use my own data set? 
I figured out the second question about the metadata. I looked into relation_metadata directory and I understand the format of all files in the directory.

**Comment by papisw** [comment]
I try running the code without the graph directory. I can see that the code tries to create it. However, I get an error "Exception in thread "main" java.lang.IllegalStateException: No step given to produce required file." Note that I have already specified "relation file" to be a path of labeled_edges.tsv  
Any suggestion how to fix this is greatly appreciated.

**Comment by matt-gardner** [comment]
Sorry to be slow and terse; I was on vacation, and just got back.

The code needs to construct the graph itself; the data download you linked to contains a graph that's already been constructed by my code.  In order to construct the graph, you need to give it the right parameters, which is basically just a list of relation set parameters.  You can see an example of this [here](https://github.com/matt-gardner/pra/blob/f72d25d94ac69487f6cd6a5a430fc4b3ed370d59/examples/experiment_specs/fb15k/sfe.json#L2-L14).  Specifics for how the relation set parameters work can be found in the [documentation](http://matt-gardner.github.io/pra/input/graphs.html) (that documentation is generally a little out of date, but I think the page I linked to is ok).

If you still can't get it working, paste in your experiment specification, and the whole output of the code, and I'll see what I can do.

**Comment by papisw** [comment]
Thank you so much for your response.
I have another quick question. I see in the documentation that split directory requires 3 things. I can run with "final_nell_split_with_negatives" file. 
Is there a way to automatically generate contents in split from the graph? It seems like the example you pointed me to automatically add negative instances. However, when I use that example, I get an error that there is no "relations_ro_run.tsv" file.

**Comment by matt-gardner** [comment]
Yes, the code will automatically generate a split from a graph if you want.  You can see an example of how to do that [here](https://github.com/matt-gardner/pra/blob/f72d25d94ac69487f6cd6a5a430fc4b3ed370d59/examples/experiment_specs/debugging/create_final_nell_split.json#L3-L12).

**Comment by papisw** [comment]
I am able to run a code but after running for a while I get a runtime error.
java.lang.RuntimeException: Nonzero exit code returned from runner: 137
	at scala.sys.package$.error(package.scala:27)

I create a graph from label_edges.tsv containing ~ 18M instances. Is there any way I can fix this?

**Comment by matt-gardner** [comment]
That line by itself is pretty meaningless.  If I'm going to be able to help you at all, I'll need much more info.  At the least, I need a full stack trace.  Even better would be the whole command that you ran, its entire output, and the experiment specification that you used.

**Comment by papisw** [comment]
I just sent you the information to your email.

Thanks a lot.

**Comment by matt-gardner** [comment]
Can you post that info here?  It's better to have the conversation in a place that's publicly available, so that others who might have the same problem can find it.

Also, the output that you sent me didn't actually have a stack trace, so I still can't help you.  It looks like it might be a memory issue, but without a stack trace, I can't tell for sure (it could also be a formatting issue with your data file, or something else).  When you do post the information here, can you make sure it's formatted correctly (with newlines), and that you run the command to get the full stack trace?

**Comment by papisw** [comment]
I will do that. Previously I ran with nohup command and I cannot see the full stack trace. I try running it again and now I can see the problem: 
[info] Split not found at ./examples/splits/pubmed_with_negatives/; creating it...
[info] Creating split at ./examples/splits/pubmed_with_negatives/
[error] Exception in thread "main" java.io.FileNotFoundException: ./examples/relation_metadata/pubmed/relations/concept:ISA (No such file or directory)
[error]         at java.io.FileInputStream.open0(Native Method)
...
 
I only give label_edges.tsv as an input. Do I also have to provide relations directory as input or it can be automatically created?

**Comment by matt-gardner** [comment]
Oh yes, this is something that I don't think is documented, and could probably be handled better.  You're missing a file that you need to generate.

Your experiment spec looks like this (from the email you sent me):
```json
{
  "graph": {
    "name": "pubmed/test",
    "relation sets": [
      {
        "is kb": false,
        "relation file": "/pra/examples/relation_metadata/pubmed/label_edges.tsv"
      },
    ]
  },
  "split": {
    "name": "pubmed_with_negatives",
    "relation metadata": "pubmed",
    "graph": "pubmed/test",
    "percent training":0.8,
    "relations":["concept:ISA"],
    "negative instances": {
      "negative to positive ratio": 10
    }
  },
  "operation": {
    "type": "train and test",
    "learning": {
      "max training examples": 5000
    }
  }
}
```

The field `split.relations = ["concept:ISA"]` defines which relations to create a split for, you just have one here.  The [`SplitCreator` code](https://github.com/matt-gardner/pra/blob/f72d25d94ac69487f6cd6a5a430fc4b3ed370d59/src/main/scala/edu/cmu/ml/rtw/pra/data/SplitCreator.scala#L88) looks for a file in the relation metadata called `/path/to/metadata/relations/[relation]`, which contains a list of node pairs in the graph.  It's just a subset of the `labeled_edges` file, formatted a little differently (just the node pairs, with the relation in the filename).  So you need to create that file.

Also, note that in order to correctly generate negative instances, you'll need to have a domain and range file in the relation metadata, with an entry for `concept:ISA` in both, and corresponding [`category_instances/[category]`](https://github.com/matt-gardner/pra/blob/f72d25d94ac69487f6cd6a5a430fc4b3ed370d59/src/main/scala/edu/cmu/ml/rtw/pra/data/SplitCreator.scala#L191) files.

**Comment by papisw** [comment]
I run into another problem. I get this error: 
[info] # There is insufficient memory for the Java Runtime Environment to continue.
[info] # Native memory allocation (mmap) failed to map 1411383296 bytes for committing reserved memory.
[info] # An error report file with more information is saved as:
[info] # /pra/hs_err_pid4308.log
[error] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f7f75c80000, 1411383296, 0) failed; error='Cannot allocate memory' (errno=12)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1966)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1966)
        at scala.Option.foreach(Option.scala:236)
        at sbt.BuildCommon$class.toError(Defaults.scala:1966)
        at sbt.Defaults$.toError(Defaults.scala:39)
        at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:734)
        at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:732)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:run) Nonzero exit code returned from runner: 1

I try sbt -mem .... but it doesn't seem to work.

**Comment by matt-gardner** [comment]
The heap size setting is in [`build.sbt`](https://github.com/matt-gardner/pra/blob/f72d25d94ac69487f6cd6a5a430fc4b3ed370d59/build.sbt#L13).  The default is 140g (!), and it appears you do not have that much memory in your machine.  You should lower that number until it matches what you have available.

**Comment by sahisnu** [comment]
Hi Matt,

I ran the pra code for emnlp_2015 paper, (sbt "run ./examples sfe_bfs_pra_anyrel") and it ran fine. I followed your documentation and then, tried to run your code for a different dataset ( a sample of  wordnet). The ExperimentRunner code ran successfully. However, I found strange results after running the ExperimentScorer. It showed AP more than 1 which is absurd. I think, there might be some problem with my code settings or my understanding of the setup. Can you please help me to figure out what's wrong.

here is the Snapshot of results:

<img width="1087" alt="screen shot 2017-01-10 at 8 52 38 pm" src="https://cloud.githubusercontent.com/assets/11520663/21833302/d48df832-d776-11e6-862c-cd76d3b292e3.png">

My experiment specification file:

<img width="815" alt="screen shot 2017-01-10 at 8 57 34 pm" src="https://cloud.githubusercontent.com/assets/11520663/21833390/7af1fd22-d777-11e6-9913-33fccc2f4ac0.png">

The input to the code provided for the wordnet experiment - a tsv file representing graph data in edge list format, train and test data for each relations while include also negative instances, relations_to_run, and param.json file all kept under the split folder.
The param.json looks like:

<img width="534" alt="screen shot 2017-01-10 at 9 17 40 pm" src="https://cloud.githubusercontent.com/assets/11520663/21834390/53bacd58-d77a-11e6-9d0d-ae93ba903879.png">

Besides, while investigating the cause of the problem, I also found that in the score file of a given relation under results folder, the number of test instances which the classifier has generated score for, is less than that provided in the corresponding test file (under split folder). E.g., for relation "_derivationally_related_from", the test file contains 1250 cases, whereas in the score file of that relation, I found 931 (considering line gaps) entries. I'm confused why it's behaving like that. 

If you need any more info, please acknowledge me.

Thanks!

**Comment by matt-gardner** [comment]
Unfortunately, I don't have a whole lot of bandwidth to help you figure this out.  But you can try to figure this out by looking here: https://github.com/matt-gardner/pra/blob/master/src/main/scala/edu/cmu/ml/rtw/pra/experiments/Metrics.scala#L64-L73.  The only way for AP to be greater than one is if there is a mismatch between the predictions you're scoring and the test file you read (either there are duplicate predictions that are getting counted, or there are positive instances in your prediction file that don't show up in your test file, for some reason).  I'm not sure how this would have happened.

**Comment by sahisnu** [comment]
Hi Matt,

Thanks for your reply. you were right; there were some duplicate entries in my own train and test data. I resolved it but somehow still, precision were more than 1. I found that a significant number of test instances have not appeared in the score files after prediction (don't know why!!). 

(1) Alternatively, I followed your previous posts in this forum and tried to generate train and test data using your code. I provided all relation metadata and the graph as edgelist format. Here is my new specification file:

<img width="787" alt="screen shot 2017-01-15 at 10 54 37 pm" src="https://cloud.githubusercontent.com/assets/11520663/21971376/a4a69e50-db75-11e6-9362-b7717a05f1a0.png">

The code ran successfully without any error. But, this time, the code generated train and test data with **no positive instances (only negative instances were there in the train and test files!)** producing incorrect results in ExperimentScorer.

I also found that number of positive features generated during training is 0 (**see 6th line from end in the snapshot**). However, the code also recognizes there were 1000 positive instances while generating the negative samples using PPR (**See 4th line from the beginning in the snapshot**) See the snapshot here:

<img width="724" alt="screen shot 2017-01-15 at 11 04 11 pm" src="https://cloud.githubusercontent.com/assets/11520663/21971553/37a160d6-db77-11e6-8131-5847106c295a.png">

Am I missing anything? I am sending you the modfied codebase for wordnet for reference.

[pra_SFE_2015_wordnet.zip](https://github.com/matt-gardner/pra/files/707295/pra_SFE_2015_wordnet.zip)

I know you're busy. But, it will be great if you kindly look into that in your spare time.

--------------
(2) Also, I tried to run the following specification file (As shown in your documentation) to evaluate the result on original pra algo:

<img width="795" alt="screen shot 2017-01-15 at 11 16 52 pm" src="https://cloud.githubusercontent.com/assets/11520663/21971701/b7503004-db78-11e6-9ab4-b6529c8607ea.png">

However, I got following error:

<img width="1052" alt="screen shot 2017-01-15 at 11 18 58 pm" src="https://cloud.githubusercontent.com/assets/11520663/21971733/00820c20-db79-11e6-83c3-6e2779a54882.png">

Can you please tell me what should I do to properly set it up.

Thanks in Advance!

**Comment by matt-gardner** [comment]
For (1), my best guess is that you formatted your edge list file as SVO, and code expects it as SOV.  Check the `edge_dict.tsv` and `node_dict.tsv` files, and make sure that the things you expect to be relations are in `edge_dict.tsv`, and the things you expect to be nodes are in `node_dict.tsv`.  The only way you could get no positive instances is if the code didn't find any edges of type `_part_of` or `_hypernym` in the graph.

For (2), when you get a "malformed parameters" message, that means that you need to fix something in your specification file.  Sadly, the documentation is out of date, so you really need to look at the code (or a known-working example) to figure out the right parameters (PRs to improve this situation are very welcome).  Do a search in the code for the name that appears in the error message ("Malformed parameters under [name]" - in your case it's "base").  I'm realizing that this one is particularly tricky to find in the code, so the name should probably be switched, but it's [here](https://github.com/matt-gardner/pra/blob/f72d25d94ac69487f6cd6a5a430fc4b3ed370d59/src/main/scala/edu/cmu/ml/rtw/pra/experiments/Driver.scala#L59).  Above that line, you can see the list of allowed parameters.  What was "pra parameters" has changed to "operation", and you should look at more recent examples of how the "operation" field is used in a specification file.

**Comment by sahisnu** [comment]
Thanks for the quick response. I have followed SOV format. You can see it in the zip file. For quick reference, here is the snapshot of wordnet_edgelist_baseline.tsv file:

<img width="463" alt="screen shot 2017-01-15 at 11 55 05 pm" src="https://cloud.githubusercontent.com/assets/11520663/21972281/0cf9029c-db7e-11e6-84bf-fcd1b2be1628.png">

I think the code generates the graph (and eventually node_dict and edge_dict) by the reading the SOV triples in the mentioned file. see the snapshots which shows '_part_of' and '_hypernym' and its id as 5 and 19. 

<img width="436" alt="screen shot 2017-01-15 at 11 58 59 pm" src="https://cloud.githubusercontent.com/assets/11520663/21972366/9af4d800-db7e-11e6-8c67-ee89b88d25f5.png">

Also, node_dict is as follows:

<img width="257" alt="screen shot 2017-01-16 at 12 00 27 am" src="https://cloud.githubusercontent.com/assets/11520663/21972392/cabb6bc6-db7e-11e6-984a-d8ca5db308db.png">

Also, you can see in the snapshots in my previous post that the code do recognize that there are 1000 positive instances for the given relation while sampling negative instances while training but doesn't generate features for the positive instances which is strange!
 
Thanks!

**Comment by matt-gardner** [comment]
Ok, sorry, looks like there was one key paragraph I missed from your earlier post.  I'm not totally sure what's going on here.  How many positive instances are there at training time?  Add a logging statement in the same place where "Number of positive features" gets output to see how many positive _instances_ there are.  Is it also zero?  Or are there positive instances that just don't have features?

**Comment by sahisnu** [comment]
Hi Matt,

Thanks for the clue. I debugged the code and found out the problem. It's running fine now.

Now, I tried to run the original pra code using the following specification file:

<img width="410" alt="screen shot 2017-01-17 at 8 38 07 pm" src="https://cloud.githubusercontent.com/assets/11520663/22048786/e3e530a6-dcf4-11e6-9828-2e2f0415d32d.png">

And I encountered following error:

<img width="811" alt="screen shot 2017-01-17 at 8 39 32 pm" src="https://cloud.githubusercontent.com/assets/11520663/22048802/0caab3bc-dcf5-11e6-94c0-25d3d2858ef8.png">

I think, the code needs graphchi files for proper execution. And I guess I have to do something with the GraphCreator file in the code repo. Can you please tell me how to easily resolve the issue as I have very little knowledge about how the graphchi code works?

Thanks!

**Comment by matt-gardner** [comment]
Was the problem a bug in this codebase?

Also, because most of the recent methods don't need to have graphchi files, I switched the default to just create a binary graph file, which loads faster with large graphs.  To create a graph with files suitable for use with graphchi, you need to set these two parameters to true in your specification file: https://github.com/matt-gardner/pra/blob/master/src/main/scala/edu/cmu/ml/rtw/pra/graphs/GraphCreator.scala#L65-L66.

**Comment by sahisnu** [comment]
Thanks for the response. yes, there was a bug, It was only returning negative instances, without appending negative instances with the positive ones. I edited the code as follows:

<img width="832" alt="screen shot 2017-01-20 at 12 31 52 am" src="https://cloud.githubusercontent.com/assets/11520663/22138750/d4248af4-dea7-11e6-9bf2-c591ffe37db1.png">

I resolved the issue. Now, I edited and ran the code to generate the graphchi files and code is working fine.

Thanks a lot matt for your time and responses!

**Comment by matt-gardner** [comment]
I see; the bug is here: https://github.com/matt-gardner/pra/blob/f72d25d94ac69487f6cd6a5a430fc4b3ed370d59/src/main/scala/edu/cmu/ml/rtw/pra/data/SplitCreator.scala#L214.  Instead of adding negative examples, like the method name implies, I'm just returning the negative examples.  I've never actually used this particular graph creation code path, which is why the bug hadn't been found before.

**Comment by sahisnu** [comment]
I tried to run the binarized pra code with the following specification:

<img width="410" alt="screen shot 2017-01-20 at 5 57 51 pm" src="https://cloud.githubusercontent.com/assets/11520663/22169470/ed48b036-df39-11e6-8aa8-4ee73d189560.png">

But, it always get stuck in the middle as you can see below. Is there any particular reason behind that? 

<img width="698" alt="screen shot 2017-01-20 at 5 52 56 pm" src="https://cloud.githubusercontent.com/assets/11520663/22169456/d3bca7ee-df39-11e6-9a2b-da0a3c93306e.png">
 
I waited for long...but it didn't proceed further.

**Comment by matt-gardner** [comment]
Unfortunately I don't have any bright ideas on this one.  Are you swapping?  It says the engine finished, so I'm not sure why it's still running.  Honestly, it's been so long since I touched anything related to graphchi, I don't know what's going on there.  Does it work if you run this: https://github.com/matt-gardner/pra/blob/master/examples/experiment_specs/nell/final_emnlp2015/baseline.json?

**Comment by sahisnu** [comment]
No, all specifications involving "RandomWalkPathFinder" have same effect. I guess there might be some processes or threads, which were running and not been stopped. I have no idea what the 7426 stands for as you see in the screenshot! I am running the code on server with 132GB RAM and 32 cores. I am quite doubtful whether memory swapping is an issue here.

Apart from that,  I found that SFE version doesn't support "RandomWalkPathFinder", it only supports BFSPathFinder. Is there any quick way to fix that in your code? 

I was running the following specification file, but it didn't work:

<img width="367" alt="screen shot 2017-01-21 at 2 48 22 pm" src="https://cloud.githubusercontent.com/assets/11520663/22177691/b34af790-dfe8-11e6-902a-94dd3a3c1955.png">

**Comment by matt-gardner** [comment]
SFE doesn't support the random walk path finder because you really want to do a BFS, not random walks, when you're running SFE.  I changed the API to be more efficient in the case that you're doing a BFS, but it made it so the current RandomWalkPathFinder can't support it.  If you really want to do this, you should modify [these lines](https://github.com/matt-gardner/pra/blob/d54f83d54bcb0d29e196869bcc001deb16ad56d3/src/main/scala/edu/cmu/ml/rtw/pra/features/SubgraphFeatureGenerator.scala#L64-L68) to use the methods that operate on datasets, instead of the methods that operate on instances.  You could just look at an old commit to see what it used to look like, and just changing it to that should work.  Though, it's likely you would run into the same issue of graphchi hanging.

As far as why graphchi is hanging, I unfortunately don't have any more ideas.  Sorry.  Maybe you could figure something out with a profiler or debugger, but that's not a very appealing option...  Or you could check out an older version of the code, around the time of the commit that added the final EMNLP2015 experiment specs, as that code should run the experiments without hanging.  

And really, the only point of graphchi is to be able to use large graphs that don't fit in memory.  If the graph fits in memory, you can just implement a very simple random walk on the in-memory graph.  It'd be pretty easy to modify the BfsPathFinder to sample instead of returning all possible paths.  Not sure how much effort you want to put into this, though...

**Comment by sahisnu** [comment]
Ok.. I got it.  Thanks a lot matt for the feedback.

**Comment by SimonZhao777** [comment]
Hi @sahisnu @matt-gardner , did you solve the graphchi hanging problem at last? I am facing a similar problem here when running pra baseline with my own dataset,  the last logger output looks almost like yours except that after I waited for a long time at this line '[error] 10:27:02 pathcompanion getPathCounts - t:1 信息:   Getting paths' '', the program pop an out of memory exception which I understand it might be the limited RAM of my mac(16G), but what I really worry about is that the program might NOT run correctly as you can see numerous "[error]" tags here in the log. if it was really purely an memory issue then I can switch to run it on server which memory won't be an issue anymore, but if it is the program running unexpectedly then I might dig into the code and see what's really going on or try checking out an older version.

POSSIBLE QUICK FIX?
As @sahisnu mentioned previously, does this long waiting behaviour always happen when the "path finder.type was set to 'RandomWalkPathFinder'"? I can switch the pra baseline json to using 'BfsPathFinder' if that's what need to be done.

**below is my config for pra baseline:**
{
  "graph": {
    "name": "alipay",
    "relation sets": [
      {
        "is kb": true,
        "relation file": "/Users/simon/IdeaProjects/pra/resource/graph_sov.tsv"
      }
    ],
    "deduplicate edges": false,
    "output binary file": false,
    "output plain text file": true,
    "shard plain text graph": true,
    "output matrices": true
  },
  "split": "alipay_with_negatives",
  "operation": {
    "type": "train and test",
    "features": {
      "type": "pra",
      "path finder": {
        "type": "RandomWalkPathFinder",
        "walks per source": 100,
        "path finding iterations": 3,
        "path accept policy": "paired-only"
      },
      "path selector": {
        "number of paths to keep": 1000
      },
      "path follower": {
        "walks per path": 50,
        "matrix accept policy": "paired-targets-only"
      }
    },
    "learning": {
      "binarize features": false,
      "l1 weight": 0.005,
      "l2 weight": 1.0
    }
  }
}

**below is the log of my last run:**
[info] =====================================
[info] Active walks: 8310900, initialized=8310900
[info] =====================================
[error] 10:26:40 engine load - t:1 信息:   Error: Tried to read past file: 1960808 --- 3921616
[error] 10:26:40 engine determineNextWindow - t:1 信息:   Memory budget: 1258291200
[error] 10:26:40 engine run - t:1 信息:   Subinterval:: 245101 -- 490201 (iteration 2)
[error] 10:26:40 engine run - t:1 信息:   Init vertices...
[error] 10:26:40 engine run - t:1 信息:   Loading...
[error] 10:26:40 engine loadBeforeUpdates - t:1 信息:   Memshard: 245101 -- 490201
[error] 10:26:40 engine loadBeforeUpdates - t:1 信息:   Loading memory-shard finished.main
[error] 10:26:40 engine run - t:1 信息:   Load took: 81ms
[error] 10:26:40 drunkard-driver beginSubInterval - t:1 信息:   Grab snapshot took 0 ms.
[error] 10:26:46 engine execUpdates - t:1 信息:   Waiting for execution to finish: countDown:64
[error] 10:26:47 pathcompanion _processWalks - t:27 信息:   Processing 262144 took 6381 ms.
[error] 10:26:48 engine execUpdates - t:1 信息:   Waiting for execution to finish: countDown:44
[error] 10:26:50 engine execUpdates - t:1 信息:   Waiting for execution to finish: countDown:44
[error] 10:26:52 engine execUpdates - t:1 信息:   Waiting for execution to finish: countDown:25
[error] 10:26:52 pathcompanion _processWalks - t:27 信息:   Processing 262144 took 1055 ms.
[error] 10:26:52 engine run - t:1 信息:   Update exec: 12193 ms.
[error] 10:26:52 long-walk-manager restoreUngrabbed - t:1 信息:   Restored 0
[error] 10:26:52 engine run - t:1 信息:   Engine finished in: 62.674 secs.
[error] 10:26:52 engine run - t:1 信息:   Updates: 1153445
[error] 10:26:54 pathcompanion getPathCounts - t:1 信息:   Waiting for finish
[error] 10:26:54 pathcompanion waitForFinish - t:1 信息:   Waiting for processing to finish
[error] 10:27:02 pathcompanion getPathCounts - t:1 信息:   Getting paths
[error] 10:55:35 path-finder shutDown - t:1 信息:   Path Finder shutting down
[info] SELECTING PATH TYPES - MostFrequentPathTypeSelector
[info] Computing feature values
[info] No range file found! (looked in nullranges.tsv)
[error] 10:55:36 walk-manager <init> - t:1 信息:   Initial size for walk bucket: 32
[error] 10:55:36 path-follower execute - t:1 信息:   Creating feature matrix using random walks
[error] 10:55:36 long-walk-manager initializeWalks - t:1 信息:   Calculate sizes. Walks length:3830
[error] 10:55:36 long-walk-manager initializeWalks - t:1 信息:   Expand capacities
[error] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
[error] 	at edu.cmu.graphchi.walks.LongWalkManager.expandCapacity(LongWalkManager.java:121)
[error] 	at edu.cmu.graphchi.walks.LongWalkManager.initializeWalks(LongWalkManager.java:156)
[error] 	at edu.cmu.graphchi.walks.DrunkardDriver.initWalks(DrunkardDriver.java:98)
[error] 	at edu.cmu.graphchi.walks.DrunkardMobEngine.run(DrunkardMobEngine.java:147)
[error] 	at edu.cmu.ml.rtw.pra.features.RandomWalkPathFollower.execute(RandomWalkPathFollower.java:129)
[error] 	at edu.cmu.ml.rtw.pra.features.PraFeatureGenerator.computeFeatureValues(PraFeatureGenerator.scala:124)
[error] 	at edu.cmu.ml.rtw.pra.features.PraFeatureGenerator.createTrainingMatrix(PraFeatureGenerator.scala:42)
[error] 	at edu.cmu.ml.rtw.pra.operations.TrainAndTest.runRelation(Operation.scala:98)
[error] 	at edu.cmu.ml.rtw.pra.experiments.Driver$$anonfun$_runStep$1.apply(Driver.scala:93)
[error] 	at edu.cmu.ml.rtw.pra.experiments.Driver$$anonfun$_runStep$1.apply(Driver.scala:87)
[error] 	at scala.collection.immutable.Stream.foreach(Stream.scala:594)
[error] 	at edu.cmu.ml.rtw.pra.experiments.Driver._runStep(Driver.scala:87)
[error] 	at com.mattg.pipeline.Step.runStep(Step.scala:187)
[error] 	at com.mattg.pipeline.Step._runPipeline(Step.scala:152)
[error] 	at com.mattg.pipeline.Step.runPipeline(Step.scala:79)
[error] 	at edu.cmu.ml.rtw.pra.experiments.ExperimentRunner$.runPraFromSpec(ExperimentRunner.scala:76)
[error] 	at edu.cmu.ml.rtw.pra.experiments.ExperimentRunner$$anonfun$runPra$1.apply(ExperimentRunner.scala:61)
[error] 	at edu.cmu.ml.rtw.pra.experiments.ExperimentRunner$$anonfun$runPra$1.apply(ExperimentRunner.scala:61)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at edu.cmu.ml.rtw.pra.experiments.ExperimentRunner$.runPra(ExperimentRunner.scala:61)
[error] 	at edu.cmu.ml.rtw.pra.experiments.ExperimentRunner$.main(ExperimentRunner.scala:31)
[error] 	at edu.cmu.ml.rtw.pra.experiments.ExperimentRunner.main(ExperimentRunner.scala)

**Comment by matt-gardner** [comment]
The earlier part of what you see as `[error]` is just graphchi printing logging statements to stderr, it's not actually a problem.  The stack trace at the end is a problem, though, and it means you need more RAM.

**Comment by SimonZhao777** [comment]
Thanks, I will try it on server with large RAM.
