### ISSUE TITLE
feature selection

### ISSUE THREAD

**Issue by IdelCoder** [matt-gardner/pra#20]
Having run the code according to the instruction on http://rtw.ml.cmu.edu/emnlp2015_sfe/, I cannot figure out when the feature selection is done. Aren't the features selected before creating feature matrix?

**Comment by matt-gardner** [comment]
All of the code around generating feature matrices is here: https://github.com/matt-gardner/pra/tree/master/src/main/scala/edu/cmu/ml/rtw/pra/features.

For PRA, the code for computing the feature matrix (including selecting features) is here: https://github.com/matt-gardner/pra/blob/d54f83d54bcb0d29e196869bcc001deb16ad56d3/src/main/scala/edu/cmu/ml/rtw/pra/features/PraFeatureGenerator.scala#L40-L43

For SFE, the code for computing the feature matrix (which does no feature selection) is here: https://github.com/matt-gardner/pra/blob/d54f83d54bcb0d29e196869bcc001deb16ad56d3/src/main/scala/edu/cmu/ml/rtw/pra/features/SubgraphFeatureGenerator.scala#L64-L68

**Comment by IdelCoder** [comment]
Thank you so much.
