### ISSUE TITLE
Why PRA performs better than SFE ?

### ISSUE THREAD

**Issue by jialiangs** [matt-gardner/pra#24]
Hello, Matt,

I have successfully run SFE and PRA. However, I found that PRA had better precision and accuracy than SFE. I guess that it is may because I set the feature size in SFE to -1 so that there are too many features in the experiment which may influence the result. And below are my configuration files.

Thank you in advance!

"""
{
  "graph": {
    "name": "yago_sfe"
    "relation sets": [
    	"load relation_sets/yago"
    ]
  },
  "split": "yago",
  "operation": {
    "features": {
      "type": "subgraphs",
      "path finder": {
        "type": "BfsPathFinder",
        "number of steps": 3
      },
      "feature extractors": [
        "PraFeatureExtractor",
        "AnyRelFeatureExtractor"
      ],
      "feature size": -1
    }
    "learning": {
      "l1 weight": 0.001,
      "l2 weight": 0.01
    }
  }
}
"""

"""
{
  "graph": {
    "name": "yago_pra"
    "relation sets": [
    	"load relation_sets/yago"
    ]
  },
  "split": "yago",
  "operation": {
    "type": "train and test",
    "features": {
      "type": "pra",
      "path finder": {
        "type": "RandomWalkPathFinder",
        "walks per source": 100,
        "path finding iterations": 3,
        "path accept policy": "paired-only"
      },
      "path selector": {
        "number of paths to keep": 1000
      },
      "path follower": {
        "walks per path":50,
        "matrix accept policy": "paired-targets-only"
      }
    }
    "learning": {
      "l1 weight": 0.005,
      "l2 weight": 0.01
    }
  }
}
"""

**Comment by matt-gardner** [comment]
Sorry, I don't have any bandwidth to look into this, nor do I have any intuitions about the difference in performance you're seeing, without looking more closely at your data.  I've long since moved on to other problems.  I'd be happy to hear the result of your exploration, though.
