### ISSUE TITLE
How can I get aliases file?

### ISSUE THREAD

**Issue by letsgowei** [matt-gardner/pra#30]
Hi Matt, i am trying to run your exprements in “Incorporating Vector Space Similarity in Random Walk Inference over Knowledge Bases. Matt Gardner, Partha Talukdar, Jayant Krishnamurthy, and Tom Mitchell. EMNLP 2014.”, but i found some data files is missed. For example, i can not find files which name is end with '.aliases'.
![image](https://user-images.githubusercontent.com/9621813/50500568-335e5f00-0a8d-11e9-8628-15415816eae3.png)

Waiting for your reply, thanks.

**Comment by matt-gardner** [comment]
If that file isn't in the data download linked on the paper website, I'm afraid it's long gone and there's nothing I can do to get it.
