### ISSUE TITLE
Memory issue of sbt

### ISSUE THREAD

**Issue by lkq1992yeah** [matt-gardner/pra#4]
Hi Matt,

I encountered a memory issue when running the program by sbt.
I specified JVM argument -Xmx40960m in the sbt configurations (I tried both $JAVA_OPTS, $SBT_OPTS, .sbtopts, and directly add -J-Xmx40960m in the running command). The sbt launcher ran with the specified JVM arg,  however this argument cannot be passed to the real program, that is, "edu.cmu.ml.rtw.pra.experiments.ExperimentRunner". Therefore I always got an OutOfMemory exception and exit within 10 minutes.

I used jps command to check JVM arguments, shown below:
kangqi@Darkstar:~/workspace/pra$ jps -vl
7512 sun.tools.jps.Jps -Dapplication.home=/usr/java/jdk1.8.0_51 -Xms8m
7464 edu.cmu.ml.rtw.pra.experiments.ExperimentRunner
7401 /usr/share/sbt-launcher-packaging/bin/sbt-launch.jar -Xms40960m -Xmx40960m -XX:ReservedCodeCacheSize=512m -XX:MaxMetaspaceSize=1024m -XX:MaxPermSize=512m

pid=7401 is the sbt launcher,  and pid=7464 is the real experiment program, which didn't assign with a Xmx argument. Have you ever encountered this situation, and could you give me some advice on this JVM configuration problem?

**Comment by matt-gardner** [comment]
You'll want to modify build.sbt, adding a line like this:

`javaOptions ++= Seq("-Xmx40g")`

Note that you'll need a blank line above and below it, or it won't compile.

**Comment by lkq1992yeah** [comment]
Yeah that works, thank you so much, and the issue could be closed.
